#!/bin/bash -e

apt autoremove -y
apt-get clean

exec apt-get -y purge \
    libreoffice \
    libreoffice-avmedia-backend-gstreamer \
    libreoffice-base \
    libreoffice-base-core \
    libreoffice-base-drivers \
    libreoffice-calc \
    libreoffice-common \
    libreoffice-core \
    libreoffice-draw \
    libreoffice-gnome \
    libreoffice-gtk3 \
    libreoffice-help-de \
    libreoffice-help-en-us \
    libreoffice-impress \
    libreoffice-java-common \
    libreoffice-l10n-de \
    libreoffice-math \
    libreoffice-pdfimport \
    libreoffice-report-builder-bin \
    libreoffice-sdbc-hsqldb \
    libreoffice-style-galaxy \
    libreoffice-style-tango \
    libreoffice-writer \
    ant \
    ant-optional \
    antlr \
    armagetronad \
    armagetronad-common \
    apache2 \
    apache2-bin \
    apache2-data \
    apache2-utils \
    amarok \
    amarok-common \
    amarok-utils \
    bitcoind \
    blinken \
    blobby \
    blobby-data \
    blobby-server \
    bluefish \
    bluefish-data \
    bluefish-plugins \
    php5-common \
    php7.0-common \
    phpmyadmin \
    php-gettext \
    chromium \
    chromium-bsu \
    chromium-bsu-data \
    chromium-l10n \
    cups \
    cups-backend-bjnp \
    cups-browsed \
    cups-bsd \
    cups-client \
    cups-common \
    cups-core-drivers \
    cups-daemon \
    cups-filters \
    cups-filters-core-drivers \
    cups-pk-helper \
    cups-ppdc \
    cups-server-common \
    curl \
    cvs \
    cvsservice \
    daisy-player \
    dia \
    dia-common \
    dia-libs \
    dia-shapes \
    dosbox \
    dosemu \
    eclipse \
    eclipse-jdt \
    eclipse-pde \
    eclipse-platform \
    eclipse-platform-data \
    eclipse-rcp \
    evolution \
    evolution-common \
    evolution-data-server \
    evolution-data-server-common \
    evolution-plugins \
    emacs \
    emacs24 \
    emacs24-bin-common \
    emacs24-common \
    emacsen-common \
    emacspeak \
    emacspeak-espeak-server \
    gnome-games \
    libmariadbclient18 \
    kate \
    kdegames-card-data \
    kdegames-mahjongg-data \
    kstars \
    openjdk-7-jdk \
    openjdk-7-jre \
    openjdk-7-jre-headless \
    mariadb-client-10.1 \
    mysql-client \
    mysql-client-5.6 \
    mysql-client-core-5.6 \
    mysql-common \
    mysql-server \
    mysql-server-5.6 \
    mysql-server-core-5.6 \
    php-seclib \
    php5 \
    php5-cli \
    php5-common \
    php5-json \
    php5-mcrypt \
    php5-mysql \
    qemu \
    qemu-kvm \
    qemu-slof \
    qemu-system \
    qemu-system-arm \
    qemu-system-common \
    qemu-system-mips \
    qemu-system-misc \
    qemu-system-ppc \
    qemu-system-sparc \
    qemu-system-x86 \
    qemu-user \
    qemu-user-binfmt \
    qemu-utils \
    scilab \
    scilab-cli \
    scilab-data \
    scilab-doc \
    scilab-full-bin \
    scilab-include \
    scilab-minimal-bin \
    spamassassin \
    spamc \
    speech-dispatcher \
    speech-dispatcher-audio-plugins \
    squid \
    squid-common \
    squid-langpack \
    tex-common \
    texinfo \
    texlive \
    texlive-base \
    texlive-binaries \
    texlive-extra-utils \
    texlive-font-utils \
    texlive-fonts-recommended \
    texlive-generic-extra \
    texlive-generic-recommended \
    texlive-lang-german \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-latex-recommended \
    texlive-luatex \
    texlive-math-extra \
    texlive-metapost \
    texlive-music \
    texlive-pictures \
    texlive-pstricks \
    texlive-science \
    texmacs \
    texmaker \
    texmaker-data \
    tuxmath \
    tuxmath-data \
    tuxpuck \
    tuxtype \
    tuxtype-data \
    tvtime \
    vlc \
    vlc-data \
    vlc-nox \
    vlc-plugin-zvbi \
    wireshark \
    wireshark-common \
    wireshark-gtk \
